services:
  - type: web
    name: securenestt
    env: python
    plan: free
    buildCommand: pip install -r SecureNestt/requirements.txt
    pythonVersion: 3.10
    startCommand: "python SecureNestt/run.py"
    envVars:
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        value: c_LwOUZz7oXKQk0rT9zjAzYx5ldMtwla9qXeAvPMxHg
